//! Short task titles generated by a one-shot, tool-less pi run.

use std::process::Stdio;
use std::time::Duration;

use anyhow::{bail, Context, Result};
use tokio::process::Command;

const TIMEOUT: Duration = Duration::from_secs(45);

pub async fn generate(pi_bin: &str, message: &str) -> Result<String> {
    let prompt = format!(
        "Write a short title (at most 6 words, no quotes, no trailing period) describing this \
         coding task request. Reply with the title only.\n\nRequest:\n{message}"
    );
    let child = Command::new(pi_bin)
        .args([
            "-p",
            "--no-session",
            "--no-tools",
            "--no-extensions",
            "--no-skills",
            "--no-prompt-templates",
            "--no-context-files",
            "--thinking",
            "off",
            &prompt,
        ])
        .stdin(Stdio::null())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .kill_on_drop(true)
        .spawn()
        .context("spawning pi for title generation")?;
    let output = tokio::time::timeout(TIMEOUT, child.wait_with_output())
        .await
        .context("pi title generation timed out")??;
    if !output.status.success() {
        bail!("pi exited with {}: {}", output.status, String::from_utf8_lossy(&output.stderr).trim());
    }
    let title = String::from_utf8_lossy(&output.stdout)
        .lines()
        .map(str::trim)
        .find(|l| !l.is_empty())
        .unwrap_or_default()
        .trim_matches(|c| c == '"' || c == '\'' || c == '.' || c == '*')
        .to_string();
    if title.is_empty() {
        bail!("pi returned an empty title");
    }
    Ok(title)
}
